# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mark/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7846.88/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/mark/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7846.88/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mark/CLionProjects/Feed-Forward-Neural-Network

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mark/CLionProjects/Feed-Forward-Neural-Network

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mark/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7846.88/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/mark/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7846.88/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mark/CLionProjects/Feed-Forward-Neural-Network/CMakeFiles /home/mark/CLionProjects/Feed-Forward-Neural-Network/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mark/CLionProjects/Feed-Forward-Neural-Network/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FNN

# Build rule for target.
FNN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FNN
.PHONY : FNN

# fast build rule for target.
FNN/fast:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/build
.PHONY : FNN/fast

FFN.o: FFN.cpp.o

.PHONY : FFN.o

# target to build an object file
FFN.cpp.o:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/FFN.cpp.o
.PHONY : FFN.cpp.o

FFN.i: FFN.cpp.i

.PHONY : FFN.i

# target to preprocess a source file
FFN.cpp.i:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/FFN.cpp.i
.PHONY : FFN.cpp.i

FFN.s: FFN.cpp.s

.PHONY : FFN.s

# target to generate assembly for a file
FFN.cpp.s:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/FFN.cpp.s
.PHONY : FFN.cpp.s

Layer.o: Layer.cpp.o

.PHONY : Layer.o

# target to build an object file
Layer.cpp.o:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/Layer.cpp.o
.PHONY : Layer.cpp.o

Layer.i: Layer.cpp.i

.PHONY : Layer.i

# target to preprocess a source file
Layer.cpp.i:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/Layer.cpp.i
.PHONY : Layer.cpp.i

Layer.s: Layer.cpp.s

.PHONY : Layer.s

# target to generate assembly for a file
Layer.cpp.s:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/Layer.cpp.s
.PHONY : Layer.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/main.cpp.s
.PHONY : main.cpp.s

utility_f.o: utility_f.cpp.o

.PHONY : utility_f.o

# target to build an object file
utility_f.cpp.o:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/utility_f.cpp.o
.PHONY : utility_f.cpp.o

utility_f.i: utility_f.cpp.i

.PHONY : utility_f.i

# target to preprocess a source file
utility_f.cpp.i:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/utility_f.cpp.i
.PHONY : utility_f.cpp.i

utility_f.s: utility_f.cpp.s

.PHONY : utility_f.s

# target to generate assembly for a file
utility_f.cpp.s:
	$(MAKE) -f CMakeFiles/FNN.dir/build.make CMakeFiles/FNN.dir/utility_f.cpp.s
.PHONY : utility_f.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... FNN"
	@echo "... FFN.o"
	@echo "... FFN.i"
	@echo "... FFN.s"
	@echo "... Layer.o"
	@echo "... Layer.i"
	@echo "... Layer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utility_f.o"
	@echo "... utility_f.i"
	@echo "... utility_f.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

